import { type LibSQLDatabase } from "drizzle-orm/libsql";
import * as schema from "./schema.js";
import type { ConversationInsert, ConversationSelect, MessageInsert, MessageSelect, ProjectInsert, ProjectSelect, TaskInsert, MemoryInsert, MemorySelect, SettingSelect, LogInsert, EmbeddingInsert, EmbeddingSelect, CronJobInsert, CronJobSelect, LlmWikiEntrySelect } from "./schema.js";
export type { LibSQLDatabase };
export * from "./schema.js";
export * from "./cron.js";
export declare class DatabaseService {
    private readonly dbPath;
    private db;
    private client;
    private logger;
    constructor(dbPath?: string);
    initialize(): Promise<void>;
    private runMigrations;
    createConversation(data: Omit<ConversationInsert, "createdAt" | "updatedAt">): Promise<ConversationSelect>;
    getConversation(id: number): Promise<ConversationSelect | undefined>;
    listConversations(projectId?: number): Promise<ConversationSelect[]>;
    listConversationsPage(args?: {
        projectId?: number;
        limit?: number;
        beforeId?: number;
    }): Promise<ConversationSelect[]>;
    deleteConversation(id: number): Promise<void>;
    addMessage(data: Omit<MessageInsert, "createdAt">): Promise<MessageSelect>;
    getMessages(conversationId: number): Promise<MessageSelect[]>;
    getMessagesPage(args: {
        conversationId: number;
        limit?: number;
        beforeId?: number;
    }): Promise<MessageSelect[]>;
    createProject(data: Omit<ProjectInsert, "createdAt" | "updatedAt">): Promise<ProjectSelect>;
    getProject(id: number): Promise<ProjectSelect | undefined>;
    listProjects(): Promise<ProjectSelect[]>;
    updateProject(id: number, data: Partial<Omit<ProjectInsert, "id" | "createdAt">>): Promise<ProjectSelect | undefined>;
    deleteProject(id: number): Promise<void>;
    createTask(data: Omit<TaskInsert, "createdAt" | "updatedAt">): Promise<schema.TaskSelect>;
    getTask(id: number): Promise<schema.TaskSelect | undefined>;
    listTasks(projectId?: number): Promise<schema.TaskSelect[]>;
    updateTask(id: number, data: Partial<Omit<TaskInsert, "id" | "createdAt">>): Promise<schema.TaskSelect | undefined>;
    deleteTask(id: number): Promise<void>;
    addMemory(data: Omit<MemoryInsert, "createdAt">): Promise<MemorySelect>;
    getMemories(conversationId?: number, type?: string, status?: string): Promise<MemorySelect[]>;
    updateMemoryStatus(id: number, status: string): Promise<MemorySelect | undefined>;
    deleteMemory(id: number): Promise<void>;
    addEmbedding(data: Omit<EmbeddingInsert, "createdAt">): Promise<EmbeddingSelect>;
    getEmbeddings(): Promise<EmbeddingSelect[]>;
    listLlmWikiEntries(limit?: number): Promise<LlmWikiEntrySelect[]>;
    getLlmWikiEntry(id: number): Promise<LlmWikiEntrySelect | undefined>;
    upsertLlmWikiEntry(data: {
        sourcePath: string;
        title: string;
        content: string;
        contentHash: string;
        status?: string;
        metadata?: string | null;
    }): Promise<LlmWikiEntrySelect>;
    deleteLlmWikiEntryBySourcePath(sourcePath: string): Promise<void>;
    deleteLlmWikiEntriesBySourcePrefix(prefix: string): Promise<number>;
    updateLlmWikiEntryStatus(id: number, status: "candidate" | "approved" | "rejected" | "error"): Promise<LlmWikiEntrySelect | undefined>;
    getSetting(key: string): Promise<string | undefined>;
    setSetting(key: string, value: string): Promise<void>;
    getAllSettings(): Promise<SettingSelect[]>;
    deleteSetting(key: string): Promise<void>;
    addLog(data: Omit<LogInsert, "timestamp">): Promise<void>;
    getLogs(level?: string, limit?: number): Promise<schema.LogSelect[]>;
    createCronJob(data: Omit<CronJobInsert, "id" | "createdAt" | "updatedAt" | "nextRunAt" | "lastRunAt" | "lastStatus" | "lastError" | "lastResult">): Promise<CronJobSelect>;
    getCronJob(id: number): Promise<CronJobSelect | undefined>;
    listCronJobs(enabledOnly?: boolean): Promise<CronJobSelect[]>;
    updateCronJob(id: number, data: Partial<Omit<CronJobInsert, "id" | "createdAt">>): Promise<CronJobSelect | undefined>;
    setCronJobRunResult(id: number, data: {
        status: "success" | "failed";
        error?: string;
        result?: string;
        nextRunAt?: string;
    }): Promise<void>;
    deleteCronJob(id: number): Promise<void>;
    get raw(): LibSQLDatabase<typeof schema>;
}
export declare function getDatabase(dbPath?: string): Promise<DatabaseService>;
//# sourceMappingURL=index.d.ts.map